name: Daily Air Quality Predictions

on:
  schedule:
    # Ejecutar diariamente a las 6:00 AM UTC (7:00 AM Madrid)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Permitir ejecución manual

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}

jobs:
  daily-predictions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.1'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libpq-dev \
          libgdal-dev \
          libproj-dev \
          libgeos-dev \
          libudunits2-dev \
          libarchive-dev \
          cmake \
          pandoc \
          gdal-bin

    - name: Cache R packages
      uses: actions/cache@v4
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION', 'renv.lock') }}

    - name: Install R dependencies
      run: |
        R -e "
        # Instalar paquetes esenciales para predicciones Y generación de mapas
        packages <- c(
          'DBI', 'RPostgres', 'caret', 'randomForest', 'sf',
          'dplyr', 'logger', 'httr2', 'jsonlite', 'lubridate',
          'data.table', 'shiny', 'leaflet', 'plotly', 'ggplot2',
          'rsconnect', 'shinydashboard', 'DT', 'htmltools',
          'shinycssloaders', 'tidyr', 'viridis', 'yaml',
          'ggrepel', 'purrr', 'gganimate', 'transformr'
        )

        # Paquetes adicionales para generación de mapas (CRÍTICOS)
        map_packages <- c('tidyterra', 'mapSpain', 'slippymath')

        # Instalar mapSpain (CRÍTICO para madrid_mask)
        tryCatch({
          if (!requireNamespace('mapSpain', quietly = TRUE)) {
            install.packages('mapSpain')
            cat('✅ mapSpain instalado - CRÍTICO para madrid_mask\n')
          } else {
            cat('⚡ mapSpain ya disponible\n')
          }
        }, error = function(e) {
          cat('❌ ERROR CRÍTICO: No se pudo instalar mapSpain:', e$message, '\n')
          cat('💡 madrid_mask no se podrá generar correctamente\n')
        })

        # Intentar instalar tidyterra desde CRAN (versión estable)
        tryCatch({
          if (!requireNamespace('tidyterra', quietly = TRUE)) {
            install.packages('tidyterra')
            cat('✅ tidyterra instalado desde CRAN\n')
          } else {
            cat('⚡ tidyterra ya disponible\n')
          }
        }, error = function(e) {
          cat('⚠️ No se pudo instalar tidyterra:', e$message, '\n')
        })

        # Intentar instalar slippymath
        tryCatch({
          if (!requireNamespace('slippymath', quietly = TRUE)) {
            install.packages('slippymath')
            cat('✅ slippymath instalado\n')
          } else {
            cat('⚡ slippymath ya disponible\n')
          }
        }, error = function(e) {
          cat('⚠️ No se pudo instalar slippymath:', e$message, '\n')
        })

        for(pkg in packages) {
          if (!requireNamespace(pkg, quietly = TRUE)) {
            install.packages(pkg)
            cat('✅ Instalado:', pkg, '\n')
          } else {
            cat('⚡ Ya disponible:', pkg, '\n')
          }
        }

        cat('✅ Dependencias esenciales instaladas\n')
        "

    - name: Download latest trained model
      run: |
        # Limpiar modelos existentes y descargar el más reciente
        rm -f models/modelos_caret_avanzados*.rds
        gh release download --pattern "modelos_caret_avanzados*.rds" --dir models/ || echo "No model found, skipping download"

        # Verificar que el modelo existe
        if [ ! -f models/modelos_caret_avanzados.rds ]; then
          echo "Error: No se pudo descargar el modelo"
          exit 1
        fi

        echo "✅ Modelo descargado correctamente"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Collect real-time data
      run: |
        # Crear directorios antes de ejecutar scripts
        mkdir -p data/realtime logs
        Rscript R/meteo_forecast.R || echo "AEMET forecast failed, continuing..."
        Rscript -e "
        source('R/datos_realtime_fallback.R', local = TRUE)
        datos_actuales <- obtener_datos_tiempo_real(usar_fallback = TRUE)
        saveRDS(datos_actuales, 'data/realtime/datos_prediccion_latest.rds')
        cat('✅ Datos actuales preparados\n')
        "
      continue-on-error: true

    - name: Generate predictions
      run: |
        # Crear directorios necesarios
        mkdir -p output data/realtime logs
        Rscript R/05_predicciones_horarias.R

    - name: Log predictions for retrospective analysis
      run: |
        Rscript -e "
        # Logging básico sin conexión a BD (por ahora)
        if (file.exists('output/predicciones_40h_latest.rds')) {
          predicciones <- readRDS('output/predicciones_40h_latest.rds')
          cat('✅ Predicciones cargadas:', nrow(predicciones), 'registros\n')

          # Generar resumen básico
          resumen <- list(
            timestamp = Sys.time(),
            total_predicciones = nrow(predicciones),
            estaciones = length(unique(predicciones\$id_estacion)),
            contaminantes = length(unique(predicciones\$contaminante)),
            rango_valores = range(predicciones\$prediccion, na.rm = TRUE)
          )

          # Guardar resumen
          saveRDS(resumen, 'output/resumen_predicciones_latest.rds')
          cat('📊 Resumen de predicciones generado\n')
        } else {
          cat('❌ No se encontraron predicciones para logging\n')
        }
        "
      continue-on-error: true

    - name: Update cloud database
      run: |
        # Verificar conexión a BD cloud (opcional)
        Rscript -e "
        tryCatch({
          library(DBI)
          library(RPostgres)

          # Conectar a BD cloud
          con <- dbConnect(RPostgres::Postgres(),
            host = Sys.getenv('DB_HOST'),
            port = as.integer(Sys.getenv('DB_PORT')),
            dbname = Sys.getenv('DB_NAME'),
            user = Sys.getenv('DB_USER'),
            password = Sys.getenv('DB_PASSWORD')
          )

          cat('✅ Conexión a cloud database exitosa\n')
          cat('📊 Tablas disponibles:', length(DBI::dbListTables(con)), '\n')

          DBI::dbDisconnect(con)
        }, error = function(e) {
          cat('⚠️ No se pudo conectar a cloud database:', e\$message, '\n')
          cat('💡 Continuando sin actualización de BD...\n')
        })
        "
      continue-on-error: true

    - name: Generate dashboard data
      run: |
        # Crear todos los directorios que podrían necesitarse
        mkdir -p app/www/mapas_horas app/www/horas app/www/logos output data/realtime logs models

        # Generar madrid_mask necesario para los mapas
        echo "🗺️ Generando madrid_mask para mapas..."
        Rscript R/00_generar_madrid_mask.R

        # Verificar que madrid_mask se generó correctamente
        if [ ! -f "data/madrid_mask.rds" ]; then
          echo "❌ Error: madrid_mask.rds no se generó"
          echo "Creando madrid_mask básico de fallback..."
          Rscript -e "
          library(sf)
          # Crear polígono básico de Madrid como fallback
          madrid_bbox <- st_bbox(c(xmin = -4.6, ymin = 40.3, xmax = -3.4, ymax = 40.7), crs = 4326)
          madrid_mask <- st_as_sfc(madrid_bbox)
          dir.create('data', showWarnings = FALSE, recursive = TRUE)
          saveRDS(madrid_mask, 'data/madrid_mask.rds')
          cat('✅ Madrid mask básico creado\n')
          "
        fi

        # Copiar madrid_mask a app/ para los scripts de mapas
        cp data/madrid_mask.rds app/madrid_mask.rds

        # Generar mapas e imágenes para el dashboard
        echo "🗺️ Generando mapas por hora..."
        if ! Rscript generar_mapas_por_hora.R; then
          echo "❌ Error generando mapas por hora"
          echo "Creando mapas de fallback..."
          mkdir -p app/www/mapas_horas
          # Copiar imagen de placeholder para evitar errores 404
          echo "Mapas no disponibles" > app/www/mapas_horas/placeholder.txt
        fi

        echo "📊 Generando imágenes por hora..."
        if ! Rscript generar_imagenes_por_hora.R; then
          echo "❌ Error generando imágenes por hora"
          echo "Creando imágenes de fallback..."
          mkdir -p app/www/horas
          echo "Imágenes no disponibles" > app/www/horas/placeholder.txt
        fi

        # Copiar datos al directorio app para Shiny
        echo "📦 Copiando datos al directorio app..."
        mkdir -p app/data
        cp output/predicciones_40h_latest.rds app/data/ || echo "Failed to copy predicciones"
        cp output/meteo_40h_latest.rds app/data/ || echo "Failed to copy meteo"

        # Verificar archivos generados
        Rscript -e "
        # Verificar predicciones y archivos dashboard
        if (file.exists('output/predicciones_40h_latest.rds')) {
          cat('✅ Predicciones generadas correctamente\n')
        } else {
          cat('❌ Error: No se generaron predicciones\n')
        }

        # Verificar mapas animados y archivos dashboard
        cat('=== VERIFICACIÓN ARCHIVOS DASHBOARD ===\n')

        # Verificar mapas por hora (críticos para animación)
        contaminantes <- c('no2', 'pm10', 'ozono')
        mapas_encontrados <- 0
        mapas_esperados <- 0

        for(cont in contaminantes) {
          for(hora in 1:10) {
            mapas_esperados <- mapas_esperados + 1
            archivo_mapa <- paste0('app/www/mapas_horas/mapa_', cont, '_hora_', sprintf('%02d', hora), '.png')
            if(file.exists(archivo_mapa)) {
              mapas_encontrados <- mapas_encontrados + 1
            }
          }
        }

        cat('📊 Mapas animados:', mapas_encontrados, 'de', mapas_esperados, 'generados\n')

        if(mapas_encontrados == 0) {
          cat('❌ ERROR CRÍTICO: No se generaron mapas animados\n')
          cat('💡 La animación no funcionará en la web\n')
        } else if(mapas_encontrados < mapas_esperados) {
          cat('⚠️ ADVERTENCIA: Mapas incompletos, algunas horas no tendrán animación\n')
        } else {
          cat('✅ Todos los mapas animados generados correctamente\n')
        }

        # Verificar algunas imágenes específicas
        imagenes_criticas <- c(
          'app/www/mapas_horas/mapa_no2_hora_01.png',
          'app/www/mapas_horas/mapa_pm10_hora_01.png',
          'app/www/horas/no2_hora_01.png'
        )

        for(img in imagenes_criticas) {
          if(file.exists(img)) {
            cat('✅ Imagen crítica:', basename(img), 'OK\n')
          } else {
            cat('❌ Imagen crítica FALTANTE:', basename(img), '\n')
          }
        }
        "

    - name: Upload prediction artifacts
      uses: actions/upload-artifact@v4
      with:
        name: daily-predictions-${{ github.run_number }}
        path: |
          output/predicciones_*.rds
          output/performance_report_*.rds
          output/mapas_realtime/
          data/realtime/
        retention-days: 7

    - name: Deploy to shinyapps.io
      run: |
        # Configurar credenciales de shinyapps.io
        Rscript -e "
        if (!requireNamespace('rsconnect', quietly = TRUE)) {
          install.packages('rsconnect')
        }

        library(rsconnect)

        # Configurar cuenta
        setAccountInfo(
          name = '${{ secrets.SHINYAPPS_NAME }}',
          token = '${{ secrets.SHINYAPPS_TOKEN }}',
          secret = '${{ secrets.SHINYAPPS_SECRET }}'
        )

        # Preparar archivos para deployment
        if (!dir.exists('deploy_temp')) dir.create('deploy_temp')

        # Copiar archivos de la app
        file.copy('app/', 'deploy_temp/', recursive = TRUE)
        file.copy('R/', 'deploy_temp/', recursive = TRUE)

        # Verificar que se copiaron los mapas animados
        mapas_copiados <- length(list.files('deploy_temp/app/www/mapas_horas/', pattern = '*.png', recursive = TRUE))
        cat('📊 Mapas copiados para deployment:', mapas_copiados, '\n')

        if(mapas_copiados == 0) {
          cat('⚠️ ADVERTENCIA: No se encontraron mapas PNG para deployment\n')
          cat('💡 La animación no funcionará en shinyapps.io\n')
        }

        # Copiar datos de predicción más recientes al directorio app
        if (!dir.exists('deploy_temp/app/data')) dir.create('deploy_temp/app/data')

        if (file.exists('output/predicciones_40h_latest.rds')) {
          file.copy('output/predicciones_40h_latest.rds', 'deploy_temp/app/data/')
        }

        if (file.exists('output/meteo_40h_latest.rds')) {
          file.copy('output/meteo_40h_latest.rds', 'deploy_temp/app/data/')
        }

        # Crear archivo de configuración de BD para la app
        writeLines(
          paste0(
            'DB_HOST=\"${{ secrets.DB_HOST }}\"\n',
            'DB_PORT=\"${{ secrets.DB_PORT }}\"\n',
            'DB_NAME=\"${{ secrets.DB_NAME }}\"\n',
            'DB_USER=\"${{ secrets.DB_USER }}\"\n',
            'DB_PASSWORD=\"${{ secrets.DB_PASSWORD }}\"'
          ),
          'deploy_temp/.Renviron'
        )

        cat('✅ Archivos preparados para deployment\n')

        # Deploy a shinyapps.io
        deployApp(
          appDir = 'deploy_temp/app',
          appName = 'madrid-air-quality',
          account = '${{ secrets.SHINYAPPS_NAME }}',
          forceUpdate = TRUE
        )

        cat('🚀 App desplegada exitosamente en shinyapps.io\n')
        cat('🔗 URL: https://${{ secrets.SHINYAPPS_NAME }}.shinyapps.io/madrid-air-quality/\n')
        "

    - name: Send success notification
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "✅ Predicciones diarias completadas - Madrid Air Quality"
        body: |
          Pipeline de predicciones ejecutado exitosamente.

          🎯 Dashboard actualizado: https://${{ secrets.SHINYAPPS_NAME }}.shinyapps.io/madrid-air-quality/
          📊 Workflow: ${{ github.workflow }}
          🔄 Run: ${{ github.run_number }}

          Próxima ejecución programada en 24 horas.
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: Madrid Air Quality System

    - name: Clean up deployment files
      run: |
        rm -rf deploy_temp
        echo "🧹 Archivos temporales limpiados"

    - name: Send email notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "❌ Error en predicciones diarias - Madrid Air Quality"
        body: |
          Ha ocurrido un error en el pipeline de predicciones diarias.

          Workflow: ${{ github.workflow }}
          Run: ${{ github.run_number }}
          Commit: ${{ github.sha }}

          Revisar logs en: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: Madrid Air Quality System